AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template for s3 bucket
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: s3-mamatha-sama-bucket1